services:
  - type: web
    name: inflow-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: REACT_APP_BACKEND_URL
        value: https://app-8ox1.onrender.com
